version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 600
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 15
  method-lines:
    config:
      threshold: 30
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
