version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  buildtest:
    jobs:
      - test35
      - test36
      - test37
      - test38

commands:
  test:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install pytest
          command: |
            python --version
            pip install pytest
            pip install coverage
            pip install pytest-cov
            pip install codecov
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Codecov
          command: codecov

jobs:
  test35:
    docker:
      - image: cimg/python3.5
    steps:
      - test

  test36:
    docker:
      - image: cimg/python3.6
    steps:
      - test

  test37:
    docker:
      - image: cimg/python3.7
    steps:
      - test

  test38:
    docker:
      - image: cimg/python3.8
    steps:
      - test
